version: '3.1'
services:

  db:
    image: mariadb
    restart: always
    ports:
      - 8889:3306
    environment:
      MARIADB_ROOT_PASSWORD: root

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  frontend:
    build:
      context: ./covid19-frontend
      dockerfile: Dockerfile
    container_name: frontend 
    ports:
      - 8081:80 

